### ISSUE TITLE
how to update sdk to adobe creatvie sdk please

### ISSUE THREAD

**Issue by pro-apps** [utsavoza/photo-editor#1]
first - great job and great design
#2- please do you will update sdk to latest adobe creative sdk ?

the app is greate but i have to isuu
wen i done editing photo and click on done
it save in DCM or PHOTOS folder 

can you add 2 things 
- wen im don editing its shows new activity with eding photo and have 2 buttons share - save
- and create save path like photos/folder name/saved photos

finaly congrats for your app and have A good day sir

**Comment by utsavoza** [comment]
i will soon update the sdk...

**Comment by pro-apps** [comment]
hi sir

thanks for response but !!

the updated code is now craching
wen im click on camera or gallery button it syes

** (unfortunately photo editor has stopped)**

its not working .. have a good day.

**Comment by pro-apps** [comment]
old cod and new code dosent work any more !!

**Comment by utsavoza** [comment]
i will check...what version of android do you run on your phone ?

**Comment by pro-apps** [comment]
4.4.2 
And dosent work with 
5.0.1 to .

**Comment by utsavoza** [comment]
Please try to import the complete project structure correctly as i have check the current build works correctly on specified target builds.....btw i didn't get your name ?

**Comment by pro-apps** [comment]
My Name is ahmed 

i will trye again and inform you if i face any problim
can you please add folder to save edit photos .

**Comment by pro-apps** [comment]
still dosent work .. same isuue
i have all libs and all things work fine but
wen i open the app in my device and click on from gallery or camera 
it forse me to close
if you have apk file you generatid it please send it to me 
so i can see if the problim comes from my android studio or device or the code itself 
thanks ..

**Comment by pro-apps** [comment]
the app work perfect in
app_debug.apk

relese apk dosent work !!!
any idea?

**Comment by utsavoza** [comment]
Don't use unaligned apk...or release apk as i haven't provided keystore for signed apk yet. app-debug.apk is the final outcome as of now

**Comment by pro-apps** [comment]
So!?
Do you solotion to bulid this app in my android studio ?!!!
Any help?
